/*
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * 
 * Triangle: T_n = n(n + 1)/2
 * Pentagonal: P_n = n(3n - 1)/2
 * Hexagonal: H_N = n(2n - 1)
 * 
 * It can be verified that T_285 = P_165 = H_143 = 40755
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

public class Euler045 {

    public static int tn = 285;
    public static int pn = 165;
    public static int hn = 143;
    public static int t = 40755, p = 40755, h = 40755;

    public static void main(String[] args) {
        nextTriangle();
        do {
            if (t < p || t < h) nextTriangle();
            if (p < t || p < h) nextPentagon();
            if (h < t || h < p) nextHexagon();
        } while (t != p || p != h);
    }

    public static void nextTriangle() { tn++; t = tn*(tn+1)/2; }
    public static void nextPentagon() { pn++; p = pn*(3*pn-1)/2; }
    public static void nextHexagon() { hn++; h = hn*(2*hn-1); }

}