/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 */

import java.util.ArrayList;

public static void main(String[] args) {
	int sum = 0;

	ArrayList<Integer> sequence = new ArrayList<Integer>(Arrays.asList(1, 2, 3, 5, 8, 13, 21, 34, 55, 89));
	int last = sequence.get(sequence.size()-1);
	int secondToLast = sequence.get(sequence.size()-2);
	while (last + secondToLast <= 4000000) {
		sequence.add(last + secondToLast);
		last = sequence.get(sequence.size()-1);
		secondToLast = sequence.get(sequence.size()-2);
	}
	for (Integer i : sequence) if (i % 2 == 0) sum += i;

	System.out.println(sum);
}